openapi: 3.0.0
info:
  title: Banking Application
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000/api/v1'
    description: Local
paths:
  /signup:
    post:
      summary: Signup
      operationId: post-signup
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      tags:
        - Client Signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                accountType:
                  type: number
              required:
                - email
                - password
                - accountType
  /signup/verify-email:
    patch:
      summary: Verify Email
      operationId: patch-signup-verify-email
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      message:
                        type: string
                  - $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                otp:
                  type: string
              required:
                - email
                - otp
      tags:
        - Client Signup
  /login:
    post:
      summary: Login
      operationId: post-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
              examples: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      message:
                        type: string
                  - $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      tags:
        - Client Login
  /account:
    get:
      summary: Get account details
      tags:
        - Client Account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  account:
                    type: object
                    properties:
                      accNumber:
                        type: string
                      balance:
                        type: number
                      accountStatus:
                        type: object
                        properties:
                          status:
                            type: string
      operationId: get-account
      security:
        - Authorization: []
  /account/transactions:
    get:
      summary: Get account transactions
      tags:
        - Client Account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: array
                    items:
                      type: object
                      properties:
                        amount:
                          type: string
                        creditDebit:
                          type: string
                        createdAt:
                          type: string
                        transactionType:
                          type: object
                          properties:
                            type:
                              type: string
                            description:
                              type: string
      operationId: get-account-transactions
      security:
        - Authorization: []
  /withdrawel:
    post:
      summary: Balance withdrawal
      operationId: post-withdrawel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      message:
                        type: string
                  - $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
      tags:
        - Client Withdrawal
  /deposit:
    post:
      summary: Make a deposit
      operationId: post-deposit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      message:
                        type: string
                  - $ref: '#/components/schemas/error'
      security:
        - Authorization: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
              required:
                - amount
      tags:
        - Client Withdrawal
  /staff/signup:
    post:
      summary: SignUp
      operationId: post-staff-signup
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      message:
                        type: string
                  - $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      tags:
        - Staff SignUp
  /staff/login:
    post:
      summary: Staff login
      operationId: post-staff-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      message:
                        type: string
                  - $ref: '#/components/schemas/error'
      tags:
        - Staff Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
components:
  schemas:
    error:
      title: validationError
      type: object
      properties:
        validationError:
          type: boolean
        errors:
          type: object
          properties:
            validationErrors:
              type: array
              items:
                type: object
                properties:
                  message:
                    type: string
      description: ''
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
security:
  - Authorization: []
